/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateICaseFileInfoModelInput = {
  _deleted?: boolean | null,
  _user?: string | null,
  id?: string | null,
  obsId: string,
  fullName?: string | null,
  first?: string | null,
  middle?: string | null,
  last?: string | null,
  suffix?: string | null,
  additional?: string | null,
  month?: string | null,
  day?: string | null,
  year?: string | null,
  date?: string | null,
  age?: string | null,
  socialSecurityNumber?: string | null,
  driversLicenseNumber?: string | null,
  passportIdentifier?: string | null,
  phones?: Array< string | null > | null,
  emails?: Array< string | null > | null,
  messagingApplications?: Array< string | null > | null,
  height?: string | null,
  weight?: string | null,
  eyeColor?: string | null,
  hairColor?: string | null,
  tattoos?: Array< string | null > | null,
  piercings?: Array< string | null > | null,
  physicalDeformities?: Array< string | null > | null,
  profile?: string | null,
  streetAddress?: string | null,
  city?: string | null,
  zip?: string | null,
  state?: string | null,
  country?: string | null,
  personalReferences?: Array< string | null > | null,
  businessReferences?: Array< string | null > | null,
  romanticReferences?: Array< string | null > | null,
  familialReferences?: Array< string | null > | null,
  outlierAssociates?: Array< string | null > | null,
};

export type ModelICaseFileInfoModelConditionInput = {
  _deleted?: ModelBooleanInput | null,
  _user?: ModelStringInput | null,
  obsId?: ModelStringInput | null,
  fullName?: ModelStringInput | null,
  first?: ModelStringInput | null,
  middle?: ModelStringInput | null,
  last?: ModelStringInput | null,
  suffix?: ModelStringInput | null,
  additional?: ModelStringInput | null,
  month?: ModelStringInput | null,
  day?: ModelStringInput | null,
  year?: ModelStringInput | null,
  date?: ModelStringInput | null,
  age?: ModelStringInput | null,
  socialSecurityNumber?: ModelStringInput | null,
  driversLicenseNumber?: ModelStringInput | null,
  passportIdentifier?: ModelStringInput | null,
  phones?: ModelStringInput | null,
  emails?: ModelStringInput | null,
  messagingApplications?: ModelStringInput | null,
  height?: ModelStringInput | null,
  weight?: ModelStringInput | null,
  eyeColor?: ModelStringInput | null,
  hairColor?: ModelStringInput | null,
  tattoos?: ModelStringInput | null,
  piercings?: ModelStringInput | null,
  physicalDeformities?: ModelStringInput | null,
  profile?: ModelStringInput | null,
  streetAddress?: ModelStringInput | null,
  city?: ModelStringInput | null,
  zip?: ModelStringInput | null,
  state?: ModelStringInput | null,
  country?: ModelStringInput | null,
  personalReferences?: ModelStringInput | null,
  businessReferences?: ModelStringInput | null,
  romanticReferences?: ModelStringInput | null,
  familialReferences?: ModelStringInput | null,
  outlierAssociates?: ModelStringInput | null,
  and?: Array< ModelICaseFileInfoModelConditionInput | null > | null,
  or?: Array< ModelICaseFileInfoModelConditionInput | null > | null,
  not?: ModelICaseFileInfoModelConditionInput | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ICaseFileInfoModel = {
  __typename: "ICaseFileInfoModel",
  _deleted?: boolean | null,
  _user?: string | null,
  id: string,
  obsId: string,
  fullName?: string | null,
  first?: string | null,
  middle?: string | null,
  last?: string | null,
  suffix?: string | null,
  additional?: string | null,
  month?: string | null,
  day?: string | null,
  year?: string | null,
  date?: string | null,
  age?: string | null,
  socialSecurityNumber?: string | null,
  driversLicenseNumber?: string | null,
  passportIdentifier?: string | null,
  phones?: Array< string | null > | null,
  emails?: Array< string | null > | null,
  messagingApplications?: Array< string | null > | null,
  height?: string | null,
  weight?: string | null,
  eyeColor?: string | null,
  hairColor?: string | null,
  tattoos?: Array< string | null > | null,
  piercings?: Array< string | null > | null,
  physicalDeformities?: Array< string | null > | null,
  profile?: string | null,
  streetAddress?: string | null,
  city?: string | null,
  zip?: string | null,
  state?: string | null,
  country?: string | null,
  personalReferences?: Array< string | null > | null,
  businessReferences?: Array< string | null > | null,
  romanticReferences?: Array< string | null > | null,
  familialReferences?: Array< string | null > | null,
  outlierAssociates?: Array< string | null > | null,
  createdAt: string,
  updatedAt: string,
};

export type UpdateICaseFileInfoModelInput = {
  _deleted?: boolean | null,
  _user?: string | null,
  id: string,
  obsId?: string | null,
  fullName?: string | null,
  first?: string | null,
  middle?: string | null,
  last?: string | null,
  suffix?: string | null,
  additional?: string | null,
  month?: string | null,
  day?: string | null,
  year?: string | null,
  date?: string | null,
  age?: string | null,
  socialSecurityNumber?: string | null,
  driversLicenseNumber?: string | null,
  passportIdentifier?: string | null,
  phones?: Array< string | null > | null,
  emails?: Array< string | null > | null,
  messagingApplications?: Array< string | null > | null,
  height?: string | null,
  weight?: string | null,
  eyeColor?: string | null,
  hairColor?: string | null,
  tattoos?: Array< string | null > | null,
  piercings?: Array< string | null > | null,
  physicalDeformities?: Array< string | null > | null,
  profile?: string | null,
  streetAddress?: string | null,
  city?: string | null,
  zip?: string | null,
  state?: string | null,
  country?: string | null,
  personalReferences?: Array< string | null > | null,
  businessReferences?: Array< string | null > | null,
  romanticReferences?: Array< string | null > | null,
  familialReferences?: Array< string | null > | null,
  outlierAssociates?: Array< string | null > | null,
};

export type DeleteICaseFileInfoModelInput = {
  id: string,
};

export type ModelICaseFileInfoModelFilterInput = {
  _deleted?: ModelBooleanInput | null,
  _user?: ModelStringInput | null,
  id?: ModelIDInput | null,
  obsId?: ModelStringInput | null,
  fullName?: ModelStringInput | null,
  first?: ModelStringInput | null,
  middle?: ModelStringInput | null,
  last?: ModelStringInput | null,
  suffix?: ModelStringInput | null,
  additional?: ModelStringInput | null,
  month?: ModelStringInput | null,
  day?: ModelStringInput | null,
  year?: ModelStringInput | null,
  date?: ModelStringInput | null,
  age?: ModelStringInput | null,
  socialSecurityNumber?: ModelStringInput | null,
  driversLicenseNumber?: ModelStringInput | null,
  passportIdentifier?: ModelStringInput | null,
  phones?: ModelStringInput | null,
  emails?: ModelStringInput | null,
  messagingApplications?: ModelStringInput | null,
  height?: ModelStringInput | null,
  weight?: ModelStringInput | null,
  eyeColor?: ModelStringInput | null,
  hairColor?: ModelStringInput | null,
  tattoos?: ModelStringInput | null,
  piercings?: ModelStringInput | null,
  physicalDeformities?: ModelStringInput | null,
  profile?: ModelStringInput | null,
  streetAddress?: ModelStringInput | null,
  city?: ModelStringInput | null,
  zip?: ModelStringInput | null,
  state?: ModelStringInput | null,
  country?: ModelStringInput | null,
  personalReferences?: ModelStringInput | null,
  businessReferences?: ModelStringInput | null,
  romanticReferences?: ModelStringInput | null,
  familialReferences?: ModelStringInput | null,
  outlierAssociates?: ModelStringInput | null,
  and?: Array< ModelICaseFileInfoModelFilterInput | null > | null,
  or?: Array< ModelICaseFileInfoModelFilterInput | null > | null,
  not?: ModelICaseFileInfoModelFilterInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelICaseFileInfoModelConnection = {
  __typename: "ModelICaseFileInfoModelConnection",
  items?:  Array<ICaseFileInfoModel | null > | null,
  nextToken?: string | null,
};

export type CreateICaseFileInfoModelMutationVariables = {
  input: CreateICaseFileInfoModelInput,
  condition?: ModelICaseFileInfoModelConditionInput | null,
};

export type CreateICaseFileInfoModelMutation = {
  createICaseFileInfoModel?:  {
    __typename: "ICaseFileInfoModel",
    _deleted?: boolean | null,
    _user?: string | null,
    id: string,
    obsId: string,
    fullName?: string | null,
    first?: string | null,
    middle?: string | null,
    last?: string | null,
    suffix?: string | null,
    additional?: string | null,
    month?: string | null,
    day?: string | null,
    year?: string | null,
    date?: string | null,
    age?: string | null,
    socialSecurityNumber?: string | null,
    driversLicenseNumber?: string | null,
    passportIdentifier?: string | null,
    phones?: Array< string | null > | null,
    emails?: Array< string | null > | null,
    messagingApplications?: Array< string | null > | null,
    height?: string | null,
    weight?: string | null,
    eyeColor?: string | null,
    hairColor?: string | null,
    tattoos?: Array< string | null > | null,
    piercings?: Array< string | null > | null,
    physicalDeformities?: Array< string | null > | null,
    profile?: string | null,
    streetAddress?: string | null,
    city?: string | null,
    zip?: string | null,
    state?: string | null,
    country?: string | null,
    personalReferences?: Array< string | null > | null,
    businessReferences?: Array< string | null > | null,
    romanticReferences?: Array< string | null > | null,
    familialReferences?: Array< string | null > | null,
    outlierAssociates?: Array< string | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateICaseFileInfoModelMutationVariables = {
  input: UpdateICaseFileInfoModelInput,
  condition?: ModelICaseFileInfoModelConditionInput | null,
};

export type UpdateICaseFileInfoModelMutation = {
  updateICaseFileInfoModel?:  {
    __typename: "ICaseFileInfoModel",
    _deleted?: boolean | null,
    _user?: string | null,
    id: string,
    obsId: string,
    fullName?: string | null,
    first?: string | null,
    middle?: string | null,
    last?: string | null,
    suffix?: string | null,
    additional?: string | null,
    month?: string | null,
    day?: string | null,
    year?: string | null,
    date?: string | null,
    age?: string | null,
    socialSecurityNumber?: string | null,
    driversLicenseNumber?: string | null,
    passportIdentifier?: string | null,
    phones?: Array< string | null > | null,
    emails?: Array< string | null > | null,
    messagingApplications?: Array< string | null > | null,
    height?: string | null,
    weight?: string | null,
    eyeColor?: string | null,
    hairColor?: string | null,
    tattoos?: Array< string | null > | null,
    piercings?: Array< string | null > | null,
    physicalDeformities?: Array< string | null > | null,
    profile?: string | null,
    streetAddress?: string | null,
    city?: string | null,
    zip?: string | null,
    state?: string | null,
    country?: string | null,
    personalReferences?: Array< string | null > | null,
    businessReferences?: Array< string | null > | null,
    romanticReferences?: Array< string | null > | null,
    familialReferences?: Array< string | null > | null,
    outlierAssociates?: Array< string | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteICaseFileInfoModelMutationVariables = {
  input: DeleteICaseFileInfoModelInput,
  condition?: ModelICaseFileInfoModelConditionInput | null,
};

export type DeleteICaseFileInfoModelMutation = {
  deleteICaseFileInfoModel?:  {
    __typename: "ICaseFileInfoModel",
    _deleted?: boolean | null,
    _user?: string | null,
    id: string,
    obsId: string,
    fullName?: string | null,
    first?: string | null,
    middle?: string | null,
    last?: string | null,
    suffix?: string | null,
    additional?: string | null,
    month?: string | null,
    day?: string | null,
    year?: string | null,
    date?: string | null,
    age?: string | null,
    socialSecurityNumber?: string | null,
    driversLicenseNumber?: string | null,
    passportIdentifier?: string | null,
    phones?: Array< string | null > | null,
    emails?: Array< string | null > | null,
    messagingApplications?: Array< string | null > | null,
    height?: string | null,
    weight?: string | null,
    eyeColor?: string | null,
    hairColor?: string | null,
    tattoos?: Array< string | null > | null,
    piercings?: Array< string | null > | null,
    physicalDeformities?: Array< string | null > | null,
    profile?: string | null,
    streetAddress?: string | null,
    city?: string | null,
    zip?: string | null,
    state?: string | null,
    country?: string | null,
    personalReferences?: Array< string | null > | null,
    businessReferences?: Array< string | null > | null,
    romanticReferences?: Array< string | null > | null,
    familialReferences?: Array< string | null > | null,
    outlierAssociates?: Array< string | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetICaseFileInfoModelQueryVariables = {
  id: string,
};

export type GetICaseFileInfoModelQuery = {
  getICaseFileInfoModel?:  {
    __typename: "ICaseFileInfoModel",
    _deleted?: boolean | null,
    _user?: string | null,
    id: string,
    obsId: string,
    fullName?: string | null,
    first?: string | null,
    middle?: string | null,
    last?: string | null,
    suffix?: string | null,
    additional?: string | null,
    month?: string | null,
    day?: string | null,
    year?: string | null,
    date?: string | null,
    age?: string | null,
    socialSecurityNumber?: string | null,
    driversLicenseNumber?: string | null,
    passportIdentifier?: string | null,
    phones?: Array< string | null > | null,
    emails?: Array< string | null > | null,
    messagingApplications?: Array< string | null > | null,
    height?: string | null,
    weight?: string | null,
    eyeColor?: string | null,
    hairColor?: string | null,
    tattoos?: Array< string | null > | null,
    piercings?: Array< string | null > | null,
    physicalDeformities?: Array< string | null > | null,
    profile?: string | null,
    streetAddress?: string | null,
    city?: string | null,
    zip?: string | null,
    state?: string | null,
    country?: string | null,
    personalReferences?: Array< string | null > | null,
    businessReferences?: Array< string | null > | null,
    romanticReferences?: Array< string | null > | null,
    familialReferences?: Array< string | null > | null,
    outlierAssociates?: Array< string | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListICaseFileInfoModelsQueryVariables = {
  filter?: ModelICaseFileInfoModelFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListICaseFileInfoModelsQuery = {
  listICaseFileInfoModels?:  {
    __typename: "ModelICaseFileInfoModelConnection",
    items?:  Array< {
      __typename: "ICaseFileInfoModel",
      _deleted?: boolean | null,
      _user?: string | null,
      id: string,
      obsId: string,
      fullName?: string | null,
      first?: string | null,
      middle?: string | null,
      last?: string | null,
      suffix?: string | null,
      additional?: string | null,
      month?: string | null,
      day?: string | null,
      year?: string | null,
      date?: string | null,
      age?: string | null,
      socialSecurityNumber?: string | null,
      driversLicenseNumber?: string | null,
      passportIdentifier?: string | null,
      phones?: Array< string | null > | null,
      emails?: Array< string | null > | null,
      messagingApplications?: Array< string | null > | null,
      height?: string | null,
      weight?: string | null,
      eyeColor?: string | null,
      hairColor?: string | null,
      tattoos?: Array< string | null > | null,
      piercings?: Array< string | null > | null,
      physicalDeformities?: Array< string | null > | null,
      profile?: string | null,
      streetAddress?: string | null,
      city?: string | null,
      zip?: string | null,
      state?: string | null,
      country?: string | null,
      personalReferences?: Array< string | null > | null,
      businessReferences?: Array< string | null > | null,
      romanticReferences?: Array< string | null > | null,
      familialReferences?: Array< string | null > | null,
      outlierAssociates?: Array< string | null > | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type OnCreateICaseFileInfoModelSubscription = {
  onCreateICaseFileInfoModel?:  {
    __typename: "ICaseFileInfoModel",
    _deleted?: boolean | null,
    _user?: string | null,
    id: string,
    obsId: string,
    fullName?: string | null,
    first?: string | null,
    middle?: string | null,
    last?: string | null,
    suffix?: string | null,
    additional?: string | null,
    month?: string | null,
    day?: string | null,
    year?: string | null,
    date?: string | null,
    age?: string | null,
    socialSecurityNumber?: string | null,
    driversLicenseNumber?: string | null,
    passportIdentifier?: string | null,
    phones?: Array< string | null > | null,
    emails?: Array< string | null > | null,
    messagingApplications?: Array< string | null > | null,
    height?: string | null,
    weight?: string | null,
    eyeColor?: string | null,
    hairColor?: string | null,
    tattoos?: Array< string | null > | null,
    piercings?: Array< string | null > | null,
    physicalDeformities?: Array< string | null > | null,
    profile?: string | null,
    streetAddress?: string | null,
    city?: string | null,
    zip?: string | null,
    state?: string | null,
    country?: string | null,
    personalReferences?: Array< string | null > | null,
    businessReferences?: Array< string | null > | null,
    romanticReferences?: Array< string | null > | null,
    familialReferences?: Array< string | null > | null,
    outlierAssociates?: Array< string | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateICaseFileInfoModelSubscription = {
  onUpdateICaseFileInfoModel?:  {
    __typename: "ICaseFileInfoModel",
    _deleted?: boolean | null,
    _user?: string | null,
    id: string,
    obsId: string,
    fullName?: string | null,
    first?: string | null,
    middle?: string | null,
    last?: string | null,
    suffix?: string | null,
    additional?: string | null,
    month?: string | null,
    day?: string | null,
    year?: string | null,
    date?: string | null,
    age?: string | null,
    socialSecurityNumber?: string | null,
    driversLicenseNumber?: string | null,
    passportIdentifier?: string | null,
    phones?: Array< string | null > | null,
    emails?: Array< string | null > | null,
    messagingApplications?: Array< string | null > | null,
    height?: string | null,
    weight?: string | null,
    eyeColor?: string | null,
    hairColor?: string | null,
    tattoos?: Array< string | null > | null,
    piercings?: Array< string | null > | null,
    physicalDeformities?: Array< string | null > | null,
    profile?: string | null,
    streetAddress?: string | null,
    city?: string | null,
    zip?: string | null,
    state?: string | null,
    country?: string | null,
    personalReferences?: Array< string | null > | null,
    businessReferences?: Array< string | null > | null,
    romanticReferences?: Array< string | null > | null,
    familialReferences?: Array< string | null > | null,
    outlierAssociates?: Array< string | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteICaseFileInfoModelSubscription = {
  onDeleteICaseFileInfoModel?:  {
    __typename: "ICaseFileInfoModel",
    _deleted?: boolean | null,
    _user?: string | null,
    id: string,
    obsId: string,
    fullName?: string | null,
    first?: string | null,
    middle?: string | null,
    last?: string | null,
    suffix?: string | null,
    additional?: string | null,
    month?: string | null,
    day?: string | null,
    year?: string | null,
    date?: string | null,
    age?: string | null,
    socialSecurityNumber?: string | null,
    driversLicenseNumber?: string | null,
    passportIdentifier?: string | null,
    phones?: Array< string | null > | null,
    emails?: Array< string | null > | null,
    messagingApplications?: Array< string | null > | null,
    height?: string | null,
    weight?: string | null,
    eyeColor?: string | null,
    hairColor?: string | null,
    tattoos?: Array< string | null > | null,
    piercings?: Array< string | null > | null,
    physicalDeformities?: Array< string | null > | null,
    profile?: string | null,
    streetAddress?: string | null,
    city?: string | null,
    zip?: string | null,
    state?: string | null,
    country?: string | null,
    personalReferences?: Array< string | null > | null,
    businessReferences?: Array< string | null > | null,
    romanticReferences?: Array< string | null > | null,
    familialReferences?: Array< string | null > | null,
    outlierAssociates?: Array< string | null > | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};
