/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateICaseFileInfoModel = /* GraphQL */ `
  subscription OnCreateICaseFileInfoModel {
    onCreateICaseFileInfoModel {
      _deleted
      _user
      id
      obsId
      fullName
      first
      middle
      last
      suffix
      additional
      month
      day
      year
      date
      age
      socialSecurityNumber
      driversLicenseNumber
      passportIdentifier
      phones
      emails
      messagingApplications
      height
      weight
      eyeColor
      hairColor
      tattoos
      piercings
      physicalDeformities
      profile
      streetAddress
      city
      zip
      state
      country
      personalReferences
      businessReferences
      romanticReferences
      familialReferences
      outlierAssociates
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateICaseFileInfoModel = /* GraphQL */ `
  subscription OnUpdateICaseFileInfoModel {
    onUpdateICaseFileInfoModel {
      _deleted
      _user
      id
      obsId
      fullName
      first
      middle
      last
      suffix
      additional
      month
      day
      year
      date
      age
      socialSecurityNumber
      driversLicenseNumber
      passportIdentifier
      phones
      emails
      messagingApplications
      height
      weight
      eyeColor
      hairColor
      tattoos
      piercings
      physicalDeformities
      profile
      streetAddress
      city
      zip
      state
      country
      personalReferences
      businessReferences
      romanticReferences
      familialReferences
      outlierAssociates
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteICaseFileInfoModel = /* GraphQL */ `
  subscription OnDeleteICaseFileInfoModel {
    onDeleteICaseFileInfoModel {
      _deleted
      _user
      id
      obsId
      fullName
      first
      middle
      last
      suffix
      additional
      month
      day
      year
      date
      age
      socialSecurityNumber
      driversLicenseNumber
      passportIdentifier
      phones
      emails
      messagingApplications
      height
      weight
      eyeColor
      hairColor
      tattoos
      piercings
      physicalDeformities
      profile
      streetAddress
      city
      zip
      state
      country
      personalReferences
      businessReferences
      romanticReferences
      familialReferences
      outlierAssociates
      createdAt
      updatedAt
    }
  }
`;
